name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: sudo apt-get install libboost-dev libboost-filesystem-dev libboost-thread-dev libboost-program-options-dev libmorph-dev libmagick++-dev libxml2-dev libnewmat10-dev
    - name: make build directory
      run: mkdir build
    - name: change to build directory
      run: cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
      
